#!/usr/bin/env bash
# Regenerate ci_benchmarks.deps.txt from ci_benchmarks.txt.
#
# The benchmarks in ci_benchmarks.txt reference other in-tree HeCBench dirs via
# '../<dir>' (sibling *-cuda data dirs, shared include/, etc.). The test_hecbench
# CI job must check those out too, or the builds fail to resolve their inputs.
# This script resolves that set transitively at the pinned HECBENCH_REF and
# writes it to ci_benchmarks.deps.txt, so CI can do a single sparse checkout of
# ci_benchmarks.txt + ci_benchmarks.deps.txt instead of a discover-then-expand
# second pass.
#
# Re-run after editing ci_benchmarks.txt or bumping HECBENCH_REF, then commit the
# updated ci_benchmarks.deps.txt:
#   .github/hecbench/update_deps.sh
# HECBENCH_REF defaults to the pin in ../workflows/spirv-ci-linux.yml; override
# via the env var. HECBENCH_REPO overrides the clone URL.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIST="$SCRIPT_DIR/ci_benchmarks.txt"
OUT="$SCRIPT_DIR/ci_benchmarks.deps.txt"
REPO="${HECBENCH_REPO:-https://github.com/ORNL/HeCBench.git}"

if [[ -z "${HECBENCH_REF:-}" ]]; then
    HECBENCH_REF=$(grep -oP 'HECBENCH_REF:\s*\K\S+' \
        "$SCRIPT_DIR/../workflows/spirv-ci-linux.yml")
fi
[[ -n "$HECBENCH_REF" ]] || { echo "HECBENCH_REF not set and not found in workflow" >&2; exit 1; }

mapfile -t benches < <(grep -vE '^[[:space:]]*(#|$)' "$LIST")
[[ ${#benches[@]} -gt 0 ]] || { echo "no benchmarks listed in $LIST" >&2; exit 1; }

echo "Resolving deps for ${#benches[@]} benchmarks at $HECBENCH_REF ..."

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
git init -q "$work"
cd "$work"
git remote add origin "$REPO"
# Shallow, blob-less: fetch only the pinned commit's trees; blobs come lazily on
# checkout. Mirrors the CI checkout so this validates that path too.
git fetch -q --depth=1 --filter=blob:none origin "$HECBENCH_REF"
git sparse-checkout init --no-cone

# want = set of src/<dir> to materialize; seed with the benchmarks, then expand
# to their transitive '../' references until the set stops growing.
declare -A want=()
for b in "${benches[@]}"; do want["src/$b"]=1; done

apply_sparse() {
    local paths=() p
    while IFS= read -r p; do paths+=("/$p/"); done \
        < <(printf '%s\n' "${!want[@]}" | sort)
    git sparse-checkout set --no-cone "${paths[@]}"
    git checkout -q FETCH_HEAD
}

apply_sparse
changed=1
while (( changed )); do
    changed=0
    while IFS= read -r d; do
        [[ -z "$d" ]] && continue
        if [[ -z "${want[src/$d]:-}" ]]; then
            want["src/$d"]=1
            changed=1
        fi
    done < <(
        for p in "${!want[@]}"; do
            [[ -d "$p" ]] || continue
            # '|| true': a dir with no '../' ref makes grep exit 1, which under
            # pipefail+errexit would abort this subshell and truncate the scan.
            grep -rhoE '\.\./[A-Za-z0-9_.-]+' "$p" 2>/dev/null | sed 's#\.\./##' || true
        done | sort -u | grep -vE '^\.' || true )
    (( changed )) && apply_sparse
done

declare -A isbench=()
for b in "${benches[@]}"; do isbench["$b"]=1; done

{
    cat <<'EOF'
# GENERATED by update_deps.sh — do not edit by hand.
# In-tree HeCBench dirs referenced (transitively) via '../' by the benchmarks in
# ci_benchmarks.txt: sibling *-cuda data dirs, shared include/, etc. The
# test_hecbench CI job checks these out alongside the benchmarks so their builds
# resolve. Regenerate with .github/hecbench/update_deps.sh (see that script).
EOF
    for p in $(printf '%s\n' "${!want[@]}" | sort); do
        d="${p#src/}"
        [[ -n "${isbench[$d]:-}" ]] && continue
        # Only real dirs at this ref; drops false positives from '../' tokens in
        # comments (e.g. NVIDIA SDK boilerplate paths in shrUtils.cu).
        [[ -d "$p" ]] || continue
        printf '%s\n' "$d"
    done
} > "$OUT"

ndeps=$(grep -cvE '^[[:space:]]*(#|$)' "$OUT" || true)
echo "Wrote $ndeps dependency dirs to $OUT"
